let list =[{
    id:2,
    text:"车站",
    disabled:true,
    autofocus:false,
    btn:true,
    write_end:true,
    isHidden:false,
    focusState: false,
  },
  {
      id:3,
      text:"城市",
      disabled:true,
      autofocus:false,
      btn:true,
      write_end:true,
      isHidden:false,
      focusState: false,
    },
    {
        id:4,
        text:"山水",
        disabled:true,
        autofocus:false,
        btn:true,
        write_end:true,
        isHidden:false,
        focusState: false,
      },
      {
        id:5,
        text:"路边",
        disabled:true,
        autofocus:false,
        btn:true,
        write_end:true,
        isHidden:false,
        focusState: false,
      },
      {
        id:6,
        text:"楼上",
        disabled:true,
        autofocus:false,
        btn:true,
        write_end:true,
        isHidden:false,
        focusState: false,
      },
      {
        id:7,
        text:"杂物间",
        disabled:true,
        autofocus:false,
        btn:true,
        write_end:true, 
        isHidden:false,
        focusState: false,
      },
      {
        id:8,
        text:"家乡",
        disabled:true,
        autofocus:false,
        btn:true,
        write_end:true,
        isHidden:false,
        focusState: false,
      },
      {
        id:9,
        text:"第三方",
        disabled:true,
        autofocus:false,
        btn:true,
        write_end:true,
        isHidden:false,
        focusState: false,
      },
      {
        id:10,
        text:"视频",
        disabled:true,
        autofocus:false,
        btn:true,
        write_end:true,
        isHidden:false,
        focusState: false,
      },
]

export default list